# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b9fef6d83cac58a4b51db2b624cac0e170387d4762f0fd6279d82b1b48ac474fddd30da426081782a626099bf20124f7f5084c4a60962d58aed5688184a7974

test:
  secret_key_base: a28ba50ed79a6d701b00e5797efe887d4d366e71a34ee17d542af06c2a6389a498fa5a2ef742e6b78b411323cbd56f25b0fd18cad68a400c0dfad8d723af1b50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
